# Project information
site_name: Intro to programming
# defeine TOC or order of website-
nav:
  - Home: index.md
  - Pre programming Basic: pre-prog-basic.md
  - Intro to programming with JavaScript:
        - Class 1 - var, data type, comparison operator: intro-to-programming-with-js-class1.md
        - Class 2 - Arithmetic operators, conditional statements: conditional-statements-class2.md
        - Class 3 - Logical operator, loop: logical-operator-loop-class3.md 
        - Class 4 - Arrary: array-class4.md
        - class 5 - Function: function-class5.md
        - Class 6 - Object: js-objects-class6.md 
  - Intro to GIS and GEE: 
     - Class 7 - Basic structure of an image: image-formation-class7.md
     - Class 8 - GIS data type and vector data in GEE: raster-vector-data-in-gee.md
     - Class 9 - GEE client VS Server: gee-client-server-side-class9.md
     - Class 10 - GEE image collection: imgcollection-class10.md
     - Class 11 - Indices calculation from imagery: indexCalculationClass11.md
     - Class 12 - Value thresholding and area calculation : mapThreasholdingclass12.md
     - Class 13 - Group Reducer and Zonal statistics  : groupReducerClass13.md
     - Class 14 - Exporting raster and vector data : exportingDataClass14.md
     - Class 15 - Supervised and unSupervised Machine learning : exportingDataClass14.md


site_author: Ramiz moktader
site_description: >-
  



# Repository
# repo_name: ramiz-moktader/
# repo_url: https://github.com/ramiz-moktader/

# Configuration
theme:
  name: material
  icon:                                                     
      logo: material/test-tube
  features:
    
    - content.code.copy
    # - content.tabs.link
    # - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.footer
    # - navigation.indexes
    # # - navigation.instant
    # # - navigation.instant.prefetch
    # # - navigation.instant.progress
    # # - navigation.prune
    # - navigation.sections
    # # - navigation.tabs
    # - navigation.tabs.sticky
    # - navigation.top
    # - navigation.tracking
    # - search.highlight
    # - search.share
    # - search.suggest
    # - toc.follow
    - navigation.instant
    - navigation.tracking
    - navigation.top
    - search.highlight
    - search.share
    # - toc.integrate

  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: teal
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime    
  # logo: PyTorch_logo_icon.svg
  
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/ramiz-moktader/
    # - icon: fontawesome/brands/twitter
    #   link: https://github.com/ramiz-moktader/
    # - icon: fontawesome/brands/linkedin
    #   link: https://github.com/ramiz-moktader/
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/groups/902693884377077 

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js #?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - toc:
      permalink: true
  - attr_list
  - md_in_html
extra_css:
  - stylesheets/extra.css
  
plugins:
  - search
# extra:
#   generator: false
copyright: |
  &copy; 2024 <a href="https://github.com/ramiz-moktader/"  target="_blank" rel="noopener"> Ramiz moktader</a>